[window]
decorations = "Full"
title = "Terminal"
opacity = 0.8
blur = true

[env]
TERM = "screen-256color"
# TERM = "alacritty"

[font]
size = 18.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[terminal]
shell = "/opt/homebrew/bin/zsh"
osc52 = "CopyPaste"

[general]
import = ["~/.config/alacritty/kanagawa.toml"]
